name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Flake8 on bots and tests directories
      run: |
        # Остановить сборку, если есть ошибки стиля
        flake8 bots tests --count --select=E9,F63,F7,F82 --show-source --statistics
        # Выход с нулём, если только предупреждения
        flake8 bots tests --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run unittest
      run: |
        python -m unittest discover -s tests
  
